from pathlib import Path
import numpy as np,csv,json,sqlite3,hashlib
r=Path(__file__).resolve().parents[1];p=r/'build/research311';d=np.load(p/'data.npz');x=d['x'];v=d['v'];t=d['t'];fold=d['fold'];y=t/v-1
width=1.15;alpha=.07

def fit(a,y):
 mean=a.mean(0);scale=np.maximum(a.std(0),.005);z=(a-mean)/scale
 distance=np.maximum(0,(z*z).sum(1)[:,None]+(z*z).sum(1)[None,:]-2*z@z.T)/z.shape[1]
 kernel=np.exp(-distance/(2*width*width));bias=float(np.median(y));weights=np.linalg.solve(kernel+alpha*np.eye(len(z)),y-bias)
 return mean,scale,z,weights,bias

def predict(xx,model):
 mean,scale,z,w,bias=model;a=(xx-mean)/scale;distance=np.maximum(0,(a*a).sum(1)[:,None]+(z*z).sum(1)[None,:]-2*a@z.T)/z.shape[1]
 return bias+np.exp(-distance/(2*width*width))@w
model=fit(x,y);corr=predict(x,model);pred=v*(1+corr);cv=np.zeros(len(x));guards=np.ones(len(x),bool)
for f in range(6):
 tr=fold!=f;te=~tr;cv[te]=predict(x[te],fit(x[tr],y[tr]));lo=x[tr].min(0);hi=x[tr].max(0);margin=np.maximum(.005,(hi-lo)*.25)
 guards[te]=np.all((x[te]>=lo-margin)&(x[te]<=hi+margin),axis=1)&(abs(cv[te])<=.15)&(v[te]>=v[tr].min()*.8)&(v[te]<=v[tr].max()*1.2)
assert np.max(abs(corr))<.15
metrics=dict(pairs=len(x),features=190,width=width,ridge=alpha,training_mape=float(np.mean(abs(pred/t-1))*100),training_max=float(np.max(abs(pred/t-1))*100),group_cv_mape=float(np.mean(abs(v*(1+cv)/t-1))*100),guarded_cv_mape=float(np.mean(abs(v*(1+np.where(guards,cv,0))/t-1))*100),validation='Exploratory six vehicle/dataset folds used for model selection; all 271 pairs used in final training; no blind holdout')
mean,scale,z,w,bias=model
saved=dict(mean=mean.tolist(),scale=scale.tolist(),centres=z.tolist(),weights=w.tolist(),bias=bias,width=width,metrics=metrics)
(p/'kernel-model.json').write_text(json.dumps(saved,indent=2))
rows=[a for a in csv.DictReader((p/'features.csv').open()) if a['volume']]
with (p/'kernel-validation.csv').open('w',newline='',encoding='utf-8') as f:
 writer=csv.writer(f);writer.writerow(['dataset','id','target','geometric','prediction','group_cv','guarded_group_cv'])
 for a,tt,vv,pp,cc,gg in zip(rows,t,v,pred,cv,guards):writer.writerow([a['dataset'],a['id'],tt,vv,pp,vv*(1+cc),vv*(1+cc) if gg else vv])
def array(name,data):return f'inline constexpr double {name}[]={{'+','.join(format(float(q),'.17g') for q in np.asarray(data).ravel())+'};\n'
h='// Generated by scripts/train_volume_kernel311.py. Geometry only; no IDs, labels or database values.\n#pragma once\nnamespace volumeKernelModel {\n'
h+=f'inline constexpr int featureCount=190,centreCount={len(z)};\ninline constexpr double bias={bias:.17g},width={width:.17g},volumeMin={v.min()*.8:.17g},volumeMax={v.max()*1.2:.17g};\n'
for name,a in [('mean',mean),('scale',scale),('centres',z),('weights',w),('featureMin',x.min(0)),('featureMax',x.max(0))]:h+=array(name,a)
h+='}\n';(r/'src/calibration_kernel_model.hpp').write_text(h,encoding='utf-8')
print(json.dumps(metrics,indent=2));print([(a['dataset'],a['id'],pp) for a,pp in zip(rows,pred) if int(a['id']) in [14301,8]])
