"""Fit a regularized, geometry-feature calibration. No IDs enter the model.
Full-data error is a training metric. Group CV is reported separately.
"""
from pathlib import Path
import csv,json,hashlib,numpy as np
r=Path(__file__).resolve().parents[1]
control={int(x['id']):x for x in csv.DictReader((r/'build/ngk-controls.csv').open())}
raw={int(x['id']):float(x['volume']) for x in csv.DictReader((r/'build/ngk-full-341-retest.csv').open())}
ids=sorted(control);keys=[(str(d),str(c),str(q)) for d in [60,100,160,250] for c in [.8,.9,.95,.98] for q in [.5,.9,1]]
observed={}
for x in csv.DictReader((r/'build/research35/rim.csv').open()):observed[(int(x['id']),x['divisor'],x['cut'],x['quantile'])]=float(x['volume'])
v=np.array([raw[i] for i in ids]);target=np.array([float(control[i]['total']) for i in ids])
x=np.array([[observed[(i,*key)]/raw[i]-1 for key in keys] for i in ids]);y=target/v-1
folds=np.array([int(hashlib.sha256(control[i]['truck'].encode()).hexdigest(),16)%5 for i in ids]);regularization=10.
def fit(xx,yy):
 mean=xx.mean(0);scale=np.maximum(xx.std(0),.001);z=np.column_stack([np.ones(len(xx)),(xx-mean)/scale]);penalty=np.eye(z.shape[1])*regularization;penalty[0,0]=0
 w=np.linalg.solve(z.T@z+penalty,z.T@yy);coef=w[1:]/scale;intercept=w[0]-mean@coef
 return intercept,coef
intercept,coef=fit(x,y);predicted=v*(1+intercept+x@coef);cv=np.zeros(len(ids))
for fold in range(5):
 train=folds!=fold;test=~train;b,w=fit(x[train],y[train]);cv[test]=v[test]*(1+b+x[test]@w)
metrics=dict(pairs=len(ids),trucks=len({control[i]['truck'] for i in ids}),ridge=regularization,training_mape=float(np.mean(abs(predicted/target-1))*100),group_cv_mape=float(np.mean(abs(cv/target-1))*100),training_max_percent=float(max(abs(predicted/target-1))*100),group_cv_max_percent=float(max(abs(cv/target-1))*100),features=48)
model=dict(intercept=float(intercept),coefficients=coef.tolist(),feature_min=x.min(0).tolist(),feature_max=x.max(0).tolist(),volume_min=float(v.min()*.8),volume_max=float(v.max()*1.2),metrics=metrics)
(r/'build/ngk-calibration-model.json').write_text(json.dumps(model,indent=2))
with (r/'build/ngk-calibration-validation.csv').open('w',newline='') as f:
 w=csv.writer(f);w.writerow(['id','truck','fold','target','geometric','training_prediction','group_cv_prediction'])
 for j,id in enumerate(ids):w.writerow([id,control[id]['truck'],folds[j],target[j],v[j],predicted[j],cv[j]])
def array(name,values):return 'inline constexpr double '+name+'[48]={'+','.join(format(float(z),'.17g') for z in values)+'};\n'
header='// Generated by scripts/train_ngk_calibration.py. Geometry features only.\n#pragma once\nnamespace ngkCalibrationModel {\n'
header+=f'inline constexpr double intercept={intercept:.17g},volumeMin={model["volume_min"]:.17g},volumeMax={model["volume_max"]:.17g};\n'
header+=array('coefficients',coef)+array('featureMin',x.min(0))+array('featureMax',x.max(0))+'}\n'
(r/'src/calibration_model.hpp').write_text(header)
print(json.dumps(metrics,indent=2))
