'use strict';
(() => {
const $=id=>document.getElementById(id), layers=['full','empty','cargo','context','water','loadedWater','tarp'];
const token=location.hash.slice(1); // Keep the local session in the fragment so F5 works; it is never sent in HTTP URLs.
let state=null, revision=-1, running=false, stopped=false, frame=null;
let camera={yaw:160,pitch:45,zoom:1,x:0,y:0}, matrix=null, pointer=null, buffers=new Map();
const canvas=$('scan'), gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true}), axes=$('axes'), ctx=axes.getContext('2d');
const format=(v,n=2)=>Number(v).toLocaleString('ru-RU',{minimumFractionDigits:n,maximumFractionDigits:n});
const currentScan=()=>state.full||state.empty;
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(path,init={}){const r=await fetch('/api/'+path,{...init,headers:{'X-Lase-Token':token,...init.headers}});if(!r.ok){let data;try{data=await r.json();}catch{data={error:'Нет ответа от локального сервера'};}throw Error(data.error||'Ошибка запроса');}return r;}
const manual=window.LaseManualCalculator(api,()=>state?.result?.volume);
function safely(fn){return async(...args)=>{try{await fn(...args);}catch(e){message(e.message,true);}};}
if(!gl){message('WebGL недоступен. Включите аппаратное ускорение браузера.',true);return;}
function shader(type,code){const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec3 position; attribute vec3 colour; uniform mat4 matrix; uniform float size; varying vec3 rgb; void main(){gl_Position=matrix*vec4(position,1.0);gl_PointSize=size;rgb=colour;}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,'precision mediump float; varying vec3 rgb; void main(){gl_FragColor=vec4(rgb,1.0);}'));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const pos=gl.getAttribLocation(program,'position'),col=gl.getAttribLocation(program,'colour'),mat=gl.getUniformLocation(program,'matrix'),size=gl.getUniformLocation(program,'size'),uintIndices=gl.getExtension('OES_element_index_uint');gl.enableVertexAttribArray(pos);gl.enableVertexAttribArray(col);
function getMatrix(){if(!frame)return null;const [lo,hi]=frame;const span=Math.max(...hi.map((v,i)=>v-lo[i]),1);const aspect=canvas.width/canvas.height;const radius=Math.hypot(...hi.map((v,i)=>v-lo[i]))/span;const s=Math.max(radius,.01)*1.08/Math.min(aspect,1)/camera.zoom,k=2/span;const a=camera.yaw*Math.PI/180,p=-camera.pitch*Math.PI/180,c=Math.cos(a),sn=Math.sin(a),cp=Math.cos(p),sp=Math.sin(p),center=lo.map((v,i)=>(v+hi[i])/2);
 const rows=[[c,-sn,0],[cp*sn,cp*c,-sp],[sp*sn,sp*c,cp]],scales=[1/(s*aspect),1/s,-1/20],m=new Float32Array(16);
 for(let r=0;r<3;r++){for(let j=0;j<3;j++)m[j*4+r]=rows[r][j]*k*scales[r];m[12+r]=(-rows[r].reduce((t,v,j)=>t+v*center[j],0)*k+(r===0?camera.x:r===1?camera.y:0))*scales[r];}m[15]=1;return m;
}
function projected(p){if(!matrix)return null;let x=matrix[0]*p[0]+matrix[4]*p[1]+matrix[8]*p[2]+matrix[12],y=matrix[1]*p[0]+matrix[5]*p[1]+matrix[9]*p[2]+matrix[13];return [(x+1)*axes.width/2,(1-y)*axes.height/2];}
function drawAxes(){ctx.clearRect(0,0,axes.width,axes.height);if(!$('zone').checked||!frame)return;const [lo,hi]=frame,points=Array.from({length:8},(_,i)=>lo.map((v,j)=>(i>>j)&1?hi[j]:v)),edges=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];
 const d=window.devicePixelRatio||1;ctx.lineWidth=d;ctx.setLineDash([2*d,4*d]);ctx.strokeStyle='#7e8999';ctx.beginPath();for(const [a,b] of edges){let p=projected(points[a]),q=projected(points[b]);ctx.moveTo(...p);ctx.lineTo(...q);}ctx.stroke();ctx.setLineDash([]);ctx.font=`${11*d}px Segoe UI`;let start=projected(lo);for(let j=0;j<3;j++){let p=lo.slice();p[j]=hi[j];let end=projected(p);ctx.strokeStyle=ctx.fillStyle=['#ff5252','#48f04f','#6363ff'][j];ctx.beginPath();ctx.moveTo(...start);ctx.lineTo(...end);ctx.stroke();ctx.fillText(`${['X','Y','Z'][j]}: ${format(hi[j])}`,Math.max(4,Math.min(axes.width-120*d,end[0]+7*d)),Math.max(14*d,Math.min(axes.height-5*d,end[1])));}}
function render(){canvas.dataset.camera=JSON.stringify(camera);const rect=canvas.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.round(rect.width*d)),h=Math.max(1,Math.round(rect.height*d));if(canvas.width!==w||canvas.height!==h){canvas.width=axes.width=w;canvas.height=axes.height=h;}
 gl.viewport(0,0,w,h);gl.clearColor(0,0,0,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);matrix=getMatrix();if(!matrix){ctx.clearRect(0,0,w,h);return;}gl.enable(gl.DEPTH_TEST);gl.uniformMatrix4fv(mat,false,matrix);gl.uniform1f(size,+$('pointSize').value*d);
 for(const layer of layers){if(!$(layer).checked)continue;const b=buffers.get(layer);if(!b||!b.count)continue;gl.bindBuffer(gl.ARRAY_BUFFER,b.vertex);gl.vertexAttribPointer(pos,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(col,3,gl.FLOAT,false,24,12);if(b.indices){gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b.index);gl.drawElements(gl.TRIANGLES,b.indices,b.type,0);}else gl.drawArrays(b.expanded?gl.TRIANGLES:gl.POINTS,0,b.count);}drawAxes();}
async function scene(layer){const mesh=$('mode').value==='1'||layer==='water'||layer==='loadedWater';const bytes=await (await api(`scene?layer=${layer}&mesh=${mesh?1:0}`)).arrayBuffer(),header=new DataView(bytes),n=header.getUint32(0,true),indices=header.getUint32(4,true);if(bytes.byteLength!==8+n*24+indices*4)throw Error('Неверный формат сцены');let vertices=new Float32Array(bytes,8,n*6),index=indices?new Uint32Array(bytes,8+n*24,indices):null;
 let type=gl.UNSIGNED_INT;if(index&&!uintIndices){if(n<=65535){index=new Uint16Array(index);type=gl.UNSIGNED_SHORT;}else{const expanded=new Float32Array(indices*6);for(let i=0;i<indices;i++)expanded.set(vertices.subarray(index[i]*6,index[i]*6+6),i*6);vertices=expanded;index=null;type=null;}}
 const old=buffers.get(layer);if(old){gl.deleteBuffer(old.vertex);if(old.index)gl.deleteBuffer(old.index);}const vertex=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vertex);gl.bufferData(gl.ARRAY_BUFFER,vertices,gl.STATIC_DRAW);let ib=null;if(index){ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,index,gl.STATIC_DRAW);}buffers.set(layer,{vertex,index:ib,vertices,count:vertices.length/6,indices:index?index.length:0,type,expanded:!!indices&&!index});
}
async function refreshScene(){for(const l of layers)await scene(l);render();}
function update(s){const old=state;state=s;if(old?.result?.volume&&!s.result?.volume){$('full').checked=true;$('empty').checked=!!s.empty;}const has=!!(s.full||s.empty),pair=!!s.full&&!!s.empty,v=s.result?.volume;
 $('fullName').textContent=s.full?`№ ${s.full.scan} · ${s.full.label}`:'Full не выбран';$('emptyName').textContent=s.empty?`№ ${s.empty.scan} · ${s.empty.label}`:'Empty / Reference не выбран';const shown=s.full||s.empty;$('pair').textContent=shown?`Измерение ${shown.scan} · ${format(shown.points,0)} точек`:'Откройте Full и Empty для сравнения';$('emptyHint').hidden=has;
 for(const key of ['full','empty']){const select=$(key+'Group'),m=s[key];const group=m?.group;select.replaceChildren();if(m){for(let i=0;i<2;i++)if(m.groups&(1<<i)){const o=document.createElement('option');o.value=i;o.textContent='Набор '+i;select.append(o);}select.value=group;}else{const o=document.createElement('option');o.value=-1;o.textContent='Авто';select.append(o);}select.disabled=s.busy||!m;}
 for(const id of ['calculate','align','compare'])$(id).disabled=!pair||s.busy;for(const id of ['openFull','openEmpty','openDatabase','settingsButton','stop'])$(id).disabled=s.busy;for(const id of ['png','report'])$(id).disabled=!has||s.busy;
 for(const key of ['cargo','context','water','loadedWater','tarp'])$(key).disabled=!v; $('water').disabled=!v?.waterAvailable;$('loadedWater').disabled=!v?.waterAvailable;$('tarp').disabled=!v?.waterAvailable;
 $('work').hidden=!s.busy;$('progress').value=s.progress;$('percent').textContent=s.progress+'%';$('phase').textContent=['','Совмещение сканов','Расчёт объёма','Построение слоёв'][s.phase]||'Расчёт';$('badge').textContent=s.busy?'ВЫЧИСЛЕНИЕ':v?(v.provisional?'ПРОВЕРИТЬ':'РАССЧИТАНО'):'ГОТОВО';
 $('volumeLabel').textContent=v?`${v.provisional?'Предварительно':'Оценка объёма'}: ${format(v.m3)} м³`:'';
 $('dimensions').textContent=v?.dimensions?`Кузов · внутренние размеры по Empty\nДлина: ${format(v.dimensions[0])} м\nШирина: ${format(v.dimensions[1])} м\nВысота до бортов: ${format(v.dimensions[2])} м`:'';
 const total=s.control?.total,delta=v&&total!=null?v.m3-total:null;$('control').textContent=total!=null?`TotalVolume: ${format(total,3)} м³${delta!=null?`\nРазница: ${delta>=0?'+':''}${format(delta,3)} м³\nОтклонение: ${total>0?(delta>=0?'+':'')+format(delta/total*100)+'%':'—'}`:''}`:'';
 $('dbLabel').textContent=s.databaseRecords?`SQ3 · ${format(s.databaseRecords,0)} записей${s.control?'':' · '+s.controlReason}`:'Контрольная база не загружена';
 manual.refresh();
 $('waterValue').textContent=v?.waterAvailable?format(v.water)+' м³':'';$('loadedValue').textContent=v?.waterAvailable?format(v.aboveLoad)+' м³':'';$('tarpValue').textContent=v?.waterAvailable?format(v.aboveRim)+' м³':'';
 if(s.error)message(s.error,true);else if(!s.busy){if(v)message(v.warning||`Расчёт выполнен · шаг ${format(v.step,0)} · проверьте границу груза`);else if(s.result)message(`Поворот базы: ${format(s.result.angle)}° · совпадение ${format(s.result.overlap*100,1)}%`);else if(!old)message(has?'Скан открыт. Выберите ракурс или рассчитайте объём.':'Откройте Full / пару или перетащите BIN в окно просмотра.');}
}
async function poll(){if(stopped||running)return;running=true;try{const s=await (await api('status')).json(),changed=s.revision!==revision;update(s);if(changed){const previous=revision;revision=s.revision;const shown=s.full||s.empty;if(!frame&&shown){frame=[shown.lo,shown.hi];if(!s.full)$('empty').checked=true;}if(s.result?.volume&&previous>=0&&!buffers.get('cargo')?.count){$('full').checked=false;$('cargo').checked=true;$('context').checked=true;}await refreshScene();}}catch(e){message(e.message,true);}finally{running=false;}}
async function upload(file,key,group=-1){if(!file)return;if(file.size>256*1024*1024)throw Error('Файл превышает 256 МиБ');message('Чтение '+file.name+'…');const s=await (await api(key+(group>=0?'?group='+group:''),{method:'PUT',body:file})).json();if(key!=='database'){const shown=s.full||s.empty;frame=shown?[shown.lo,shown.hi]:null;camera={yaw:160,pitch:45,zoom:1,x:0,y:0};$('full').checked=!!s.full;$('empty').checked=!s.full&&!!s.empty;$('cargo').checked=false;$('context').checked=false;}revision=-1;update(s);await poll();message(file.name+' открыт');}
async function openPair(files){const list=[...files];const full=list.find(f=>/_Full\.bin$/i.test(f.name))||list.find(f=>!/_Empty\.bin$/i.test(f.name));const empty=list.find(f=>/_Empty\.bin$/i.test(f.name));if(full)await upload(full,'full');if(empty)await upload(empty,'empty');}
$('openFull').onclick=()=>$('fullFile').click();$('openEmpty').onclick=()=>$('emptyFile').click();$('openDatabase').onclick=()=>$('databaseFile').click();$('fullFile').onchange=safely(async e=>{await openPair(e.target.files);e.target.value='';});$('emptyFile').onchange=safely(async e=>{await upload(e.target.files[0],'empty');e.target.value='';});$('databaseFile').onchange=safely(async e=>{await upload(e.target.files[0],'database');e.target.value='';});for(const key of ['full','empty'])$(key+'Group').onchange=safely(async e=>{const s=await (await api('group?layer='+key+'&group='+e.target.value,{method:'POST'})).json();const shown=s.full||s.empty;frame=[shown.lo,shown.hi];camera={yaw:160,pitch:45,zoom:1,x:0,y:0};revision=-1;update(s);await poll();});
async function compute(calculate){const step=+$('step').value;if(!Number.isFinite(step)||step<10||step>2000)throw Error('Шаг сетки должен быть от 10 до 2000');const query=new URLSearchParams({step,unit:$('unit').value,adaptive:+$('adaptive').checked,gaps:+$('gaps').checked,estimate:+$('estimate').checked});const s=await (await api((calculate?'calculate':'align')+'?'+query,{method:'POST'})).json();update(s);}
$('calculate').onclick=safely(()=>compute(true));$('align').onclick=safely(()=>compute(false));$('compare').onclick=()=>{$('full').checked=$('empty').checked=true;$('cargo').checked=$('context').checked=false;render();};$('settingsButton').onclick=()=>$('settings').showModal();
function fitPreset(){if(!frame)return;const [lo,hi]=frame,span=Math.max(...hi.map((v,i)=>v-lo[i]),1),center=lo.map((v,i)=>(v+hi[i])/2),k=2/span,a=camera.yaw*Math.PI/180,p=-camera.pitch*Math.PI/180,c=Math.cos(a),s=Math.sin(a),cp=Math.cos(p),sp=Math.sin(p);let xmin=Infinity,ymin=Infinity,xmax=-Infinity,ymax=-Infinity;
 for(const l of layers){if(!$(l).checked)continue;const vertices=buffers.get(l)?.vertices;if(!vertices)continue;for(let i=0;i<vertices.length;i+=6){let x=(vertices[i]-center[0])*k,y=(vertices[i+1]-center[1])*k,z=(vertices[i+2]-center[2])*k,u=c*x-s*y,v=cp*(s*x+c*y)-sp*z;xmin=Math.min(xmin,u);xmax=Math.max(xmax,u);ymin=Math.min(ymin,v);ymax=Math.max(ymax,v);}}
 if(!Number.isFinite(xmin))return;const aspect=canvas.clientWidth/canvas.clientHeight,radius=Math.hypot(...hi.map((v,i)=>v-lo[i]))/span,base=Math.max(radius,.01)*1.08/Math.min(aspect,1),required=Math.max((xmax-xmin)/(2*aspect),(ymax-ymin)/2,.01)*1.15;camera.zoom=Math.max(.1,Math.min(50,base/required));camera.x=-(xmin+xmax)/2;camera.y=-(ymin+ymax)/2;}
function preset(name){if(name==='reset')camera={yaw:160,pitch:45,zoom:1,x:0,y:0};else{const heading=state?.heading||0;camera={yaw:name==='top'?0:name==='front'?90-heading:-heading,pitch:name==='top'?0:90,zoom:1,x:0,y:0};fitPreset();}render();}
for(const p of ['top','front','side','reset'])$(p).onclick=()=>preset(p);for(const l of [...layers,'zone'])$(l).onchange=render;$('pointSize').oninput=render;$('mode').onchange=safely(refreshScene);$('theme').onchange=()=>document.body.classList.toggle('light',$('theme').value==='light');
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.onpointerdown=e=>{if(!frame)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,pan:e.button!==0||e.shiftKey};canvas.setPointerCapture(e.pointerId);canvas.classList.add('drag');$('viewport').focus();};canvas.onpointermove=e=>{if(!pointer||pointer.id!==e.pointerId)return;const rect=canvas.getBoundingClientRect(),dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(pointer.pan){const [lo,hi]=frame,span=Math.max(...hi.map((v,i)=>v-lo[i]),1),radius=Math.hypot(...hi.map((v,i)=>v-lo[i]))/span,s=Math.max(radius,.01)*1.08/Math.min(rect.width/rect.height,1)/camera.zoom;camera.x+=dx*2*s/rect.height;camera.y-=dy*2*s/rect.height;}else{const k=180/Math.max(300,Math.min(rect.width,rect.height));camera.yaw+=dx*k;camera.pitch=Math.max(-90,Math.min(90,camera.pitch-dy*k));}pointer.x=e.clientX;pointer.y=e.clientY;render();};
function release(){pointer=null;canvas.classList.remove('drag');}canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onlostpointercapture=release;canvas.ondblclick=()=>preset('reset');canvas.onwheel=e=>{e.preventDefault();if(!frame)return;const rect=canvas.getBoundingClientRect(),old=camera.zoom;camera.zoom=Math.max(.1,Math.min(50,camera.zoom*Math.pow(1.12,-e.deltaY/100)));const [lo,hi]=frame,span=Math.max(...hi.map((v,i)=>v-lo[i]),1),radius=Math.hypot(...hi.map((v,i)=>v-lo[i]))/span,s=Math.max(radius,.01)*1.08/Math.min(rect.width/rect.height,1)/old,f=old/camera.zoom;camera.x+=(2*(e.clientX-rect.left)/rect.width-1)*s*rect.width/rect.height*(f-1);camera.y+=(1-2*(e.clientY-rect.top)/rect.height)*s*(f-1);render();};$('viewport').onkeydown=e=>{if(e.key.toLowerCase()==='r'){preset('reset');e.preventDefault();}};
const vp=$('viewport');vp.ondragover=e=>{e.preventDefault();};vp.ondrop=safely(async e=>{e.preventDefault();if(state?.busy)throw Error('Дождитесь завершения расчёта');await openPair(e.dataTransfer.files);});
function image(){render();const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.drawImage(canvas,0,0);c.drawImage(axes,0,0);c.font='bold 22px Segoe UI';c.fillStyle='#68c85e';c.fillText($('volumeLabel').textContent,20,36);c.font='13px Segoe UI';c.fillStyle='#c1d6d6';let y=out.height-20;for(const line of $('control').textContent.split('\n').reverse()){c.fillText(line,Math.max(10,out.width-c.measureText(line).width-15),y);y-=20;}return out.toDataURL('image/png');}
async function download(data,format){await api('export?format='+format,{method:'POST',body:data});const a=document.createElement('a');a.href='/api/download?format='+format+'&key='+encodeURIComponent(token);a.download=`LaseScanViewer-${currentScan().scan}.${format}`;document.body.append(a);a.click();a.remove();}
$('png').onclick=safely(async()=>{const encoded=image().split(',')[1],raw=atob(encoded),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);await download(bytes,'png');});
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function reportUnits(volume){return ({0.001:'Миллиметры',0.01:'Сантиметры',1:'Метры'}[volume?.metresPerUnit])||$('unit').selectedOptions[0].textContent;}
$('report').onclick=safely(async()=>{const v=state.result?.volume;const text=`<!doctype html><html lang="ru"><meta charset="utf-8"><title>LaseScanViewer — отчёт</title><style>body{font:16px system-ui;max-width:1000px;margin:40px auto;padding:20px;color:#203040}img{width:100%}pre{white-space:pre-wrap;font:inherit;line-height:1.7}</style><h1>LaseScanViewer Web · 3.34.0</h1><p>Измерение ${currentScan().scan} · ${escape(currentScan().label)}</p><h2>${escape($('volumeLabel').textContent||'Просмотр скана')}</h2><pre>${escape($('dimensions').textContent)}\n${escape($('control').textContent)}</pre><p>${escape(v?.warning||'')}</p><p>Единицы координат: ${escape(reportUnits(v))}. ${v?'Фактический шаг: '+format(v.step):''}</p><img src="${image()}" alt="Текущий вид скана"><p>Исходные BIN не изменены. TotalVolume используется только для сравнения.</p></html>`;await download(new Blob([text],{type:'text/html;charset=utf-8'}),'html');});
$('stop').onclick=safely(async()=>{await api('stop',{method:'POST'});stopped=true;message('Веб-сессия закрыта. Это окно можно закрыть.');for(const b of document.querySelectorAll('button'))b.disabled=true;});
new ResizeObserver(render).observe(vp);poll();setInterval(poll,600);
})();
